### PR TITLE
Revert to using default chart scaling for handbook

### PR DESCRIPTION
**Pull request by gmintoco**
Disable scaling specification meaning deployment will fall back to default scaling

### CODE REVIEW

**Comment by comzeradd** [comment]
Ah I remembered why we can't do that on the Handbook 😁 

Handbook has a plugin that allows people to translate strings from our codebase. That plugin writes fetches `.po` files and stores/updates them locally. So having multiple pods breaks this whole functionality.

**Comment by gmintoco** [comment]
@comzeradd ah I see. How are those files persisted though? there are no persistent volumes mounted in the pod so I would expect those translations to be deleted upon a pod restart/eviction etc.?

**Comment by comzeradd** [comment]
Yes, they are deleted on deployments but that's not a problem. For every translation saved there is a CI pipeline that commits them back to the appropriate repo in a few seconds. The problem with multiple pods is that the changes temporarily with be saved to just one pod.

**Comment by gmintoco** [comment]
Ah okay got it - will close this issue then

**Pull request closed without merging**
